/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Section1; //Sook Ying Sam

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sam SY
 */
public class MainMenuPanel extends javax.swing.JPanel {
    private MainFrame mainFrame;
    String name;
    private ArrayList<Player> register;

    /**
     * Creates new form MainMenuPanel
     */
    public MainMenuPanel(MainFrame frame) {
        this.mainFrame = frame;
        initComponents();
        setSize(1920,1080);
        register = new ArrayList<>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLBL = new javax.swing.JLabel();
        playBTN = new javax.swing.JButton();
        levelBTN = new javax.swing.JButton();
        resultBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        nameLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        displayBTN = new javax.swing.JButton();
        gameStatsBTN = new javax.swing.JButton();

        titleLBL.setText("Firefigher Game");

        playBTN.setText("PLAY");
        playBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBTNActionPerformed(evt);
            }
        });

        levelBTN.setText("Level Select");
        levelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelBTNActionPerformed(evt);
            }
        });

        resultBTN.setText("Result Stats ");
        resultBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultBTNActionPerformed(evt);
            }
        });

        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        nameLBL.setText("Name");

        addBTN.setText("ADD");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        deleteBTN.setText("DELETE");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        displayBTN.setText("DISPLAY");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });

        gameStatsBTN.setText("Game Stats");
        gameStatsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameStatsBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(titleLBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteBTN)
                            .addComponent(displayBTN)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(levelBTN)
                        .addGap(51, 51, 51)
                        .addComponent(resultBTN)
                        .addGap(71, 71, 71)
                        .addComponent(gameStatsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addBTN)))
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playBTN)
                        .addGap(44, 44, 44)
                        .addComponent(exitBTN))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(230, 230, 230))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(titleLBL)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(addBTN)
                        .addGap(18, 18, 18)
                        .addComponent(displayBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLBL))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playBTN)
                            .addComponent(exitBTN))
                        .addGap(43, 43, 43)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelBTN)
                    .addComponent(resultBTN)
                    .addComponent(gameStatsBTN))
                .addGap(119, 119, 119))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_exitBTNActionPerformed

    private void playBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBTNActionPerformed
        // TODO add your handling code here:
        if(mainFrame != null){
            mainFrame.showScreen("Game");
        }
    }//GEN-LAST:event_playBTNActionPerformed

    private void levelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelBTNActionPerformed
        // TODO add your handling code here:
        if(mainFrame != null){
            mainFrame.showScreen("LevelSelect");
        }
    }//GEN-LAST:event_levelBTNActionPerformed

    private void resultBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultBTNActionPerformed
        // TODO add your handling code here:
        if(mainFrame != null){
            String playerName = nameTF.getText().trim();
            
            if(!playerName.isEmpty()) {
            File playerFile = new File(playerName + "_stats.txt");
            if(playerFile.exists()) {
                System.out.println("Loading stats for: " + playerName); 
                mainFrame.showResultsStats(playerName);
            } else {
                displayTA.setText("Player '" + playerName + "' not found. Please ADD player first.");
                System.out.println("File not found: " + playerFile.getAbsolutePath()); // Debug
            }
        } else {
            displayTA.setText("Please enter a player name first.");
        }
        }
    }//GEN-LAST:event_resultBTNActionPerformed
    
    
                                              
    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        String name = nameTF.getText().trim();
        if (!name.isEmpty()) {
            Player tempP = new Player(name);
            register.add(tempP);
            savePlayerToFile(tempP);  
            displayTA.setText("New Player Registered: " + name);
        }        
    }//GEN-LAST:event_addBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        if(register.isEmpty()){
             displayTA.setText("No players registered");
         }else{
             String searchTerm = JOptionPane.showInputDialog(null, "Enter Name to be deleted");
             for(int i = 0; i < register.size(); i++){
                 Player tempP = register.get(i);
                 if(tempP.getName().equalsIgnoreCase(searchTerm)){
                     register.remove(i);
                     displayTA.setText("Player " + searchTerm + " has been removed.");
                 }
             }
         }
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
        if(register.isEmpty()){
            displayTA.setText("No players registered.");
        }else{
            for(Player p:register){ //forEach loop
                JOptionPane.showMessageDialog(null, p.printDetails());
            }
        }
    }//GEN-LAST:event_displayBTNActionPerformed

    private void gameStatsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameStatsBTNActionPerformed
        // TODO add your handling code here:
        if(mainFrame != null){
        mainFrame.showScreen("GameStats");
    }
    }//GEN-LAST:event_gameStatsBTNActionPerformed

    private void savePlayerToFile(Player player) {
    try {
        File file = new File(player.getName() + "_stats.txt");
        PrintWriter writer = new PrintWriter(new FileWriter(file));
        
        writer.println("Level:1");
        writer.println("Score:0");
        writer.println("Lives:3");
        writer.println("Water:100");
        writer.println("Experience:0");
        
        writer.close();
    } catch (IOException e) {
        System.out.println("Error saving player: " + e.getMessage());
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton displayBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JButton exitBTN;
    private javax.swing.JButton gameStatsBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton levelBTN;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton playBTN;
    private javax.swing.JButton resultBTN;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
