/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Section1;

import javax.swing.JOptionPane;

/**
 *
 * @author Sam SY
 */
public class MainMenuPanel extends javax.swing.JPanel {
    private MainFrame mainFrame;

    /**
     * Creates new form MainMenuPanel
     */
    public MainMenuPanel(MainFrame frame) {
        this.mainFrame = frame;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLBL = new javax.swing.JLabel();
        playBTN = new javax.swing.JButton();
        levelBTN = new javax.swing.JButton();
        scoreBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();

        titleLBL.setText("Firefigher Game");

        playBTN.setText("PLAY");
        playBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBTNActionPerformed(evt);
            }
        });

        levelBTN.setText("Level Select");
        levelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelBTNActionPerformed(evt);
            }
        });

        scoreBTN.setText("Score");
        scoreBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreBTNActionPerformed(evt);
            }
        });

        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(playBTN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scoreBTN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitBTN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLBL, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(levelBTN)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleLBL)
                .addGap(18, 18, 18)
                .addComponent(playBTN)
                .addGap(18, 18, 18)
                .addComponent(levelBTN)
                .addGap(18, 18, 18)
                .addComponent(scoreBTN)
                .addGap(18, 18, 18)
                .addComponent(exitBTN)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_exitBTNActionPerformed

    private void playBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBTNActionPerformed
        // TODO add your handling code here:
        if(mainFrame != null){
            mainFrame.showScreen("Game");
        }
    }//GEN-LAST:event_playBTNActionPerformed

    private void levelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelBTNActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Level Select coming soon!");
    }//GEN-LAST:event_levelBTNActionPerformed

    private void scoreBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreBTNActionPerformed
        // TODO add your handling code here:
        if(mainFrame != null){
            mainFrame.showScreen("GameStats");
        }
    }//GEN-LAST:event_scoreBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBTN;
    private javax.swing.JButton levelBTN;
    private javax.swing.JButton playBTN;
    private javax.swing.JButton scoreBTN;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
