/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Section3;
import Section1.MainFrame;

/**
 *
 * @author Owner
 */
public class GameStatsPanel extends javax.swing.JPanel{
    
    private NavController navigator;

    /**
     * Creates new form GameStatsPanel
     */
    public GameStatsPanel(NavController navigator) {
        this.navigator = navigator;
        initComponents();
        setupGameStats();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalGamesLBL = new javax.swing.JLabel();
        completedLevelsLBL = new javax.swing.JLabel();
        totalScoreLBL = new javax.swing.JLabel();
        bestTimeLBL = new javax.swing.JLabel();
        firesExtinguishedLBL = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();
        achievementsScroll = new javax.swing.JScrollPane();
        achievementsTXT = new javax.swing.JTextArea();

        totalGamesLBL.setText("Total Games: ");

        completedLevelsLBL.setText("Completed Levels: ");

        totalScoreLBL.setText("Total Score");

        bestTimeLBL.setText("Best Time");

        firesExtinguishedLBL.setText("Fires Extinguished");

        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        achievementsTXT.setColumns(20);
        achievementsTXT.setRows(5);
        achievementsScroll.setViewportView(achievementsTXT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bestTimeLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalScoreLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                    .addComponent(firesExtinguishedLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(totalGamesLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(completedLevelsLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(achievementsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(backBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(totalGamesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(completedLevelsLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bestTimeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firesExtinguishedLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(achievementsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("MainMenu");
        }
    }//GEN-LAST:event_backBTNActionPerformed
    
    private void setupGameStats(){
        loadStatistics();
    }
    
    public void loadStatistics(){
       //loading from a txt file in the final version, just for sample set those values here
       totalGamesLBL.setText("Total Games Played: 5");
       completedLevelsLBL.setText("Completed Levels: 3");
       totalScoreLBL.setText("Total Score: 2,450");
       bestTimeLBL.setText("Best Time: 1:25");
       firesExtinguishedLBL.setText("Fires Extinguished: 28");
       achievementsTXT.setText("Achievements:\n- First Fire Extinguished\n- Level 1 Completed\n- Water Master\n- Quick Responder");
   }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane achievementsScroll;
    private javax.swing.JTextArea achievementsTXT;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel bestTimeLBL;
    private javax.swing.JLabel completedLevelsLBL;
    private javax.swing.JLabel firesExtinguishedLBL;
    private javax.swing.JLabel totalGamesLBL;
    private javax.swing.JLabel totalScoreLBL;
    // End of variables declaration//GEN-END:variables
}
