/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Section3;

import java.io.*;
import java.util.*;

/**
 *
 * @author Edgar Camacho
 */
public class ResultStatsPanel extends javax.swing.JPanel {
    
    private NavController navigator;
    private String currentUser;

    /**
     * Creates new form PlayerStatsPanel
     */
    public ResultStatsPanel(NavController navigator) {
        this.navigator = navigator;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBTN = new javax.swing.JButton();
        averageScoreLBL = new javax.swing.JLabel();
        bestScoreLBL = new javax.swing.JLabel();
        bestTimeLBL = new javax.swing.JLabel();
        totalGamesLBL = new javax.swing.JLabel();
        titleLBL = new javax.swing.JLabel();
        saveBTN = new javax.swing.JButton();
        levelLBL = new javax.swing.JLabel();
        currentScoreLBL = new javax.swing.JLabel();
        livesLBL = new javax.swing.JLabel();
        waterLBL = new javax.swing.JLabel();
        experienceBar = new javax.swing.JProgressBar();
        refreshStatsBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyOfGameTA = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        backBTN.setText("Back to the Main Menu");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        averageScoreLBL.setText("Average Score: ");

        bestScoreLBL.setText("Best Score: ");

        bestTimeLBL.setText("Best Time: ");

        totalGamesLBL.setText("Total Games Played: ");

        titleLBL.setText("Player Statistics");

        saveBTN.setText("Save");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        levelLBL.setText("Level: ");

        currentScoreLBL.setText("Current Score:");

        livesLBL.setText("Lives: ");

        waterLBL.setText("Water: ");

        refreshStatsBTN.setText("Refresh Stats");
        refreshStatsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshStatsBTNActionPerformed(evt);
            }
        });

        historyOfGameTA.setColumns(20);
        historyOfGameTA.setRows(5);
        jScrollPane1.setViewportView(historyOfGameTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(saveBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(experienceBar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(refreshStatsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bestScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(averageScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bestTimeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalGamesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(levelLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currentScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(livesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(waterLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalGamesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bestScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(averageScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(levelLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(currentScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(livesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bestTimeLBL)
                    .addComponent(waterLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(experienceBar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBTN)
                    .addComponent(refreshStatsBTN))
                .addGap(18, 18, 18)
                .addComponent(saveBTN)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("MainMenu");
        }
    }//GEN-LAST:event_backBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
            savePlayerStats(currentUser);
        } else {
            historyOfGameTA.setText("No user selected. Cannot save stats.");
        }
    }//GEN-LAST:event_saveBTNActionPerformed

    private void refreshStatsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshStatsBTNActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
            loadPlayerStats(currentUser);
        }
    }//GEN-LAST:event_refreshStatsBTNActionPerformed

    
    private List<String> readUserGames(String username){
        List<String> games = new ArrayList<>();
        try{
            File file = new File(username + "_games.txt");
            if(!file.exists()){
                return games;
            }
            BufferedReader reader = new BufferedReader(new FileReader(file));
            String line;
            while ((line = reader.readLine()) != null){
                if (!line.trim().isEmpty()) {
                    games.add(line.trim());
                }
            }
            reader.close();
        } catch (IOException e){
            System.out.println("Error reading games: " + e.getMessage());
        }
        return games;
    }
    
     private void savePlayerStats(String username) {
        try {
            File file = new File(username + "_stats.txt");
            PrintWriter writer = new PrintWriter(new FileWriter(file));
            
            writer.println("Username:" + username);
            writer.println("Level:" + levelLBL.getText().replace("Level: ", ""));
            writer.println("Score:" + currentScoreLBL.getText().replace("Current Score: ", ""));
            writer.println("Lives:" + livesLBL.getText().replace("Lives: ", ""));
            writer.println("Water:" + waterLBL.getText().replace("Water: ", ""));
            writer.println("Experience:" + experienceBar.getValue());
            
            writer.close();
            historyOfGameTA.setText("Player stats saved successfully for: " + username);
        } catch (IOException e) {
            historyOfGameTA.setText("Error saving player stats: " + e.getMessage());
        }
    }
    
     public void loadPlayerStats(String username) {
        this.currentUser = username;
        titleLBL.setText("Result - Player Statistics - " + username);
        
        try {
            File statsFile = new File(username + "_stats.txt");
            if (statsFile.exists()) {
                BufferedReader reader = new BufferedReader(new FileReader(statsFile));
                String line;
                
                while ((line = reader.readLine()) != null) {
                    String[] textParts = line.split(":");
                    if (textParts.length == 2) {
                        switch (textParts[0]) {
                            case "Username":
                                break;
                            case "Level":
                                levelLBL.setText("Level: " + textParts[1]);
                                break;
                            case "Score":
                                currentScoreLBL.setText("Current Score: " + textParts[1]);
                                break;
                            case "Lives":
                                livesLBL.setText("Lives: " + textParts[1]);
                                break;
                            case "Water":
                                waterLBL.setText("Water: " + textParts[1]);
                                break;
                            case "Experience":
                                experienceBar.setValue(Integer.parseInt(textParts[1]));
                                experienceBar.setString("Experience: " + textParts[1] + "%");
                                break;
                        }
                    }
                }
                reader.close();
            }
        } catch (IOException e) {
            System.out.println("Error loading player stats: " + e.getMessage());
        }
        
    
        List<String> games = readUserGames(this.currentUser);
        
        if (games.isEmpty()) {
            historyOfGameTA.setText("No games played yet for: " + username);
            totalGamesLBL.setText("Total Games Played: 0");
            bestScoreLBL.setText("Best Score: 0");
            averageScoreLBL.setText("Average Score: 0");
            bestTimeLBL.setText("Best Time: 0s");
            return;
        }
        
        int totalGames = games.size();
        int bestScore = 0;
        int totalScore = 0;
        int bestTime = Integer.MAX_VALUE;
        StringBuilder historyText = new StringBuilder();
        
        for (String game : games) {
            String[] parts = game.split(",");
            if (parts.length >= 3) {
                int score = Integer.parseInt(parts[0]);
                int time = Integer.parseInt(parts[1]);
                String result = parts[2];
                
                historyText.append("Score: ").append(score)
                          .append(" | Time: ").append(time).append("s")
                          .append(" | ").append(result).append("\n");
                
                if (score > bestScore) bestScore = score;
                totalScore += score;
                if (time < bestTime && time > 0) bestTime = time;
            }
        }
        
        int averageScore = totalScore / totalGames;
        
        totalGamesLBL.setText("Total Games Played: " + totalGames);
        bestScoreLBL.setText("Best Score: " + bestScore);
        averageScoreLBL.setText("Average Score: " + averageScore);
        bestTimeLBL.setText("Best Time: " + (bestTime == Integer.MAX_VALUE ? "0" : bestTime) + "s");
        historyOfGameTA.setText(historyText.toString());
    }
     
     public void updatePlayerStats(String username, int level, int score, int lives, int water, int experience) {
        this.currentUser = username;
        levelLBL.setText("Level: " + level);
        currentScoreLBL.setText("Current Score: " + score);
        livesLBL.setText("Lives: " + lives);
        waterLBL.setText("Water: " + water + "/100");
        experienceBar.setValue(experience);
        experienceBar.setString("Experience: " + experience + "%");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel averageScoreLBL;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel bestScoreLBL;
    private javax.swing.JLabel bestTimeLBL;
    private javax.swing.JLabel currentScoreLBL;
    private javax.swing.JProgressBar experienceBar;
    private javax.swing.JTextArea historyOfGameTA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel levelLBL;
    private javax.swing.JLabel livesLBL;
    private javax.swing.JButton refreshStatsBTN;
    private javax.swing.JButton saveBTN;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JLabel totalGamesLBL;
    private javax.swing.JLabel waterLBL;
    // End of variables declaration//GEN-END:variables
}
