/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Section2_Lance;

import Section3_Edgar.NavController;

/**
 *
 * @author lwild_oeg6x3t
 */
public class GamePanel extends javax.swing.JPanel {

    private NavController navigator;
    /**
     * Creates new form GamePanel
     */
    public GamePanel(NavController navigator) {
        this.navigator = navigator;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pauseBTN = new javax.swing.JButton();
        scoreLBL = new javax.swing.JLabel();
        livesLBL = new javax.swing.JLabel();
        waterLBL = new javax.swing.JLabel();
        timerLBL = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1920, 1080));

        pauseBTN.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        pauseBTN.setText("PAUSE");
        pauseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseBTNActionPerformed(evt);
            }
        });

        scoreLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        scoreLBL.setText("SCORE:");
        scoreLBL.setToolTipText("");

        livesLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        livesLBL.setText("LIVES:");

        waterLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        waterLBL.setText("WATER LEFT:");

        timerLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        timerLBL.setText("TIME LEFT:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pauseBTN)
                .addGap(305, 305, 305)
                .addComponent(livesLBL)
                .addGap(128, 128, 128)
                .addComponent(waterLBL)
                .addGap(112, 112, 112)
                .addComponent(timerLBL)
                .addGap(134, 134, 134)
                .addComponent(scoreLBL)
                .addContainerGap(465, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pauseBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scoreLBL)
                            .addComponent(timerLBL)
                            .addComponent(waterLBL)
                            .addComponent(livesLBL))))
                .addContainerGap(995, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pauseBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseBTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("PauseMenu");
        }
    }//GEN-LAST:event_pauseBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel livesLBL;
    private javax.swing.JButton pauseBTN;
    private javax.swing.JLabel scoreLBL;
    private javax.swing.JLabel timerLBL;
    private javax.swing.JLabel waterLBL;
    // End of variables declaration//GEN-END:variables
}
