/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Section2_Lance;

import Section3_Edgar.NavController;

/**
 *
 * @author Lance Wilde
 */
public class PauseMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form PauseMenuPanel
     */
    private NavController navigator;
    /**
     * Creates new form LevelSelectPanel
     */
    public PauseMenuPanel(NavController navigator) {
        this.navigator = navigator;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resumeBTN = new javax.swing.JButton();
        mainmenuBTN = new javax.swing.JButton();
        settingsBTN = new javax.swing.JButton();
        gamepausedLBL = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1920, 1080));

        resumeBTN.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        resumeBTN.setText("RESUME");
        resumeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeBTNActionPerformed(evt);
            }
        });

        mainmenuBTN.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mainmenuBTN.setText("MAIN MENU");
        mainmenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuBTNActionPerformed(evt);
            }
        });

        settingsBTN.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        settingsBTN.setText("SETTINGS");
        settingsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBTNActionPerformed(evt);
            }
        });

        gamepausedLBL.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        gamepausedLBL.setText("GAME PAUSED");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(836, 836, 836)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resumeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(settingsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainmenuBTN)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(788, 788, 788)
                        .addComponent(gamepausedLBL)))
                .addContainerGap(793, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(gamepausedLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(resumeBTN)
                .addGap(121, 121, 121)
                .addComponent(settingsBTN)
                .addGap(120, 120, 120)
                .addComponent(mainmenuBTN)
                .addGap(336, 336, 336))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resumeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeBTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("Game");
        }
    }//GEN-LAST:event_resumeBTNActionPerformed

    private void settingsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("Settings");
        }
    }//GEN-LAST:event_settingsBTNActionPerformed

    private void mainmenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuBTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("MainMenu");
        }
    }//GEN-LAST:event_mainmenuBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gamepausedLBL;
    private javax.swing.JButton mainmenuBTN;
    private javax.swing.JButton resumeBTN;
    private javax.swing.JButton settingsBTN;
    // End of variables declaration//GEN-END:variables
}
