/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Section2_Lance;

import Section1_Sam.MainFrame;
import Section3_Edgar.NavController;
import javax.swing.SwingUtilities;

/**
 *
 * @author Lance
 */
public class PauseMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form PauseMenuPanel
     */
    private NavController navigator;
    /**
     * Creates new form LevelSelectPanel
     */
    public PauseMenuPanel(NavController navigator) {
        this.navigator = navigator;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resumeBTN = new javax.swing.JButton();
        mainmenuBTN = new javax.swing.JButton();
        gamepausedLBL = new javax.swing.JLabel();

        setBackground(new java.awt.Color(139, 174, 102));
        setForeground(new java.awt.Color(255, 255, 255));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        resumeBTN.setBackground(new java.awt.Color(0, 92, 59));
        resumeBTN.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        resumeBTN.setForeground(new java.awt.Color(255, 255, 255));
        resumeBTN.setText("RESUME");
        resumeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeBTNActionPerformed(evt);
            }
        });

        mainmenuBTN.setBackground(new java.awt.Color(0, 92, 59));
        mainmenuBTN.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mainmenuBTN.setForeground(new java.awt.Color(255, 255, 255));
        mainmenuBTN.setText("MAIN MENU");
        mainmenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuBTNActionPerformed(evt);
            }
        });

        gamepausedLBL.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        gamepausedLBL.setForeground(new java.awt.Color(255, 255, 255));
        gamepausedLBL.setText("GAME PAUSED");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(836, 836, 836)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resumeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainmenuBTN)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(786, 786, 786)
                        .addComponent(gamepausedLBL)))
                .addContainerGap(795, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(gamepausedLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                .addComponent(resumeBTN)
                .addGap(141, 141, 141)
                .addComponent(mainmenuBTN)
                .addGap(412, 412, 412))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resumeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeBTNActionPerformed
        // TODO add your handling code here:
        try {
            MainFrame frame = (MainFrame) navigator;
            GamePanel gamePanel = frame.getGamePanel();

        if (gamePanel != null) {
            gamePanel.resumeGame();
        }

        // Switches to the gamepanel
        navigator.switchScreen("Game");

        // Makes sure that the gamepanel is in focus for userinputs to work properly
        SwingUtilities.invokeLater(() -> {
            gamePanel.requestFocusInWindow();
        });

    } catch (Exception e) {
        System.out.println("Resume error: " + e.getMessage());
    }
    }//GEN-LAST:event_resumeBTNActionPerformed

    private void mainmenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuBTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("MainMenu");
        }
    }//GEN-LAST:event_mainmenuBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gamepausedLBL;
    private javax.swing.JButton mainmenuBTN;
    private javax.swing.JButton resumeBTN;
    // End of variables declaration//GEN-END:variables
}
