/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Section2_Lance;

import Section3.NavController;

/**
 *
 * @author lwild_oeg6x3t
 */
public class SettingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SettingsPanel
     */
    private NavController navigator;
    
    public SettingsPanel(NavController navigator) {
        this.navigator = navigator;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsLBL = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1920, 1080));

        settingsLBL.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        settingsLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsLBL.setText("SETTINGS");

        backBTN.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(backBTN)
                .addGap(727, 727, 727)
                .addComponent(settingsLBL)
                .addContainerGap(855, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(backBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(settingsLBL)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("PauseMenu");
        }
    }//GEN-LAST:event_backBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel settingsLBL;
    // End of variables declaration//GEN-END:variables
}
