/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package Section3_Edgar;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.*;

/**
 *
 * @author Edgar Camacho
 */
public class GameStatsPanel extends javax.swing.JPanel{
    
    //defining first an instance of the navController interface to switch screens
    private NavController navigator;

   
    /**
     * Creates new form GameStatsPanel
     */
    public GameStatsPanel(NavController navigator) {
        this.navigator = navigator;
        initComponents();
        setupGameStats();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalGamesLBL = new javax.swing.JLabel();
        totalScoreLBL = new javax.swing.JLabel();
        bestScoreLBL = new javax.swing.JLabel();
        firesExtinguishedLBL = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();
        achievementsScroll = new javax.swing.JScrollPane();
        achievementsTXT = new javax.swing.JTextArea();
        bestPlayerLBL = new javax.swing.JLabel();
        achievementsLBL = new javax.swing.JLabel();
        bestTimeLBL = new javax.swing.JLabel();

        setBackground(new java.awt.Color(139, 174, 102));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153))));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        totalGamesLBL.setBackground(new java.awt.Color(255, 255, 255));
        totalGamesLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        totalGamesLBL.setForeground(java.awt.Color.white);
        totalGamesLBL.setText("Total Games: ");

        totalScoreLBL.setBackground(new java.awt.Color(255, 255, 255));
        totalScoreLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        totalScoreLBL.setForeground(java.awt.Color.white);
        totalScoreLBL.setText("Total Score: ");

        bestScoreLBL.setBackground(new java.awt.Color(255, 255, 255));
        bestScoreLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bestScoreLBL.setForeground(java.awt.Color.white);
        bestScoreLBL.setText("Best Session Score: ");

        firesExtinguishedLBL.setBackground(new java.awt.Color(255, 255, 255));
        firesExtinguishedLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        firesExtinguishedLBL.setForeground(java.awt.Color.white);

        backBTN.setBackground(new java.awt.Color(0, 92, 59));
        backBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        backBTN.setForeground(new java.awt.Color(255, 255, 255));
        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        achievementsTXT.setColumns(20);
        achievementsTXT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        achievementsTXT.setRows(5);
        achievementsScroll.setViewportView(achievementsTXT);

        bestPlayerLBL.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bestPlayerLBL.setForeground(new java.awt.Color(255, 255, 255));
        bestPlayerLBL.setText("Best Player: ");

        achievementsLBL.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        achievementsLBL.setForeground(new java.awt.Color(250, 250, 250));
        achievementsLBL.setText("Achievements");

        bestTimeLBL.setBackground(new java.awt.Color(255, 255, 255));
        bestTimeLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bestTimeLBL.setForeground(java.awt.Color.white);
        bestTimeLBL.setText("Fastest Session Time: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(514, 514, 514)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(firesExtinguishedLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalGamesLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bestScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bestTimeLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bestPlayerLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(achievementsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(achievementsLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(617, 617, 617))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bestPlayerLBL)
                        .addGap(81, 81, 81)
                        .addComponent(totalGamesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(totalScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(bestScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(firesExtinguishedLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bestTimeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(achievementsLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(achievementsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(346, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("MainMenu");
        }
    }//GEN-LAST:event_backBTNActionPerformed
    
    private void setupGameStats(){
        loadStatistics();
    }
    
    public void loadStatistics(){
        ArrayList<String> playerRegister = readAllPlayersAdded();

        if (playerRegister.isEmpty()) {
            achievementsTXT.setText("No users found in users.txt");
            bestPlayerLBL.setText("Best Player: -");
            totalGamesLBL.setText("Total Games: 0");
            totalScoreLBL.setText("Total Score: 0");
            bestScoreLBL.setText("Best Score: 0");
            bestTimeLBL.setText("Best Time: 0s");
            firesExtinguishedLBL.setText("Fires Extinguished: 0");
            return;
        }
        ArrayList<PlayerStats> allPlayersStats = new ArrayList<>();

        for (String player : playerRegister) {
            PlayerStats stats = makeStatsForPlayer(player);
            if (stats.totalGames > 0) {
                allPlayersStats.add(stats);
            }
        }

        if (allPlayersStats.isEmpty()) {
            achievementsTXT.setText("Users exist, but no game data found.");
            return;
        }
        
        PlayerStats best = allPlayersStats.get(0);
        for (PlayerStats p : allPlayersStats){
            if (p.totalScore > best.totalScore) {
            best = p;
            }
        }
        
        bestPlayerLBL.setText("Best Player: " + best.username);
        totalGamesLBL.setText("Total Sessions Played: " + best.totalGames);
        totalScoreLBL.setText("Total Score: " + best.totalScore);
        bestScoreLBL.setText("Best Session Score: " + best.bestScore);
        bestTimeLBL.setText("Fastest Session Time: " + best.bestTime + "s");
        
        AchievementManager manager = new AchievementManager();
        ArrayList<Achievement> unlocked = manager.getAchievements(best);
        
        
        if (unlocked.isEmpty()) {
            achievementsTXT.setText("No achievements unlocked.");
        } else {
            String text = "";
            for (Achievement a : unlocked) {
                text = text + "- " + a.getTitle() + ": " + a.getDescription() + "\n";
            }
            achievementsTXT.setText(text);
        }
   }
    
    private ArrayList<String> readAllPlayersAdded() {
        //this method is gonna read the file that keeps all the users added in the main menu panel
        // useful to get the best player later
        ArrayList<String> users = new ArrayList<>();

        File file = new File("users.txt");
        if (!file.exists()) {
            return users;
        }

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    users.add(line.trim());
                }
            }
        } catch (IOException e) {
            System.out.println("Error reading users.txt: " + e.getMessage());
        }

        return users;
    }
    
    private PlayerStats makeStatsForPlayer(String username) {
        PlayerStats stats = new PlayerStats(username);
        stats.username = username;
        stats.bestTime = Integer.MAX_VALUE;

    // Read all games for this user and getting totalScore, bestScore and bestTime
        ArrayList<String> games = readAllGames(username);
        stats.totalGames = games.size();

        for (String gameLine : games) {
            String[] parts = gameLine.split(",");
            if (parts.length >= 3) {
                int score = Integer.parseInt(parts[0].trim());
                int time = Integer.parseInt(parts[1].trim());

                stats.totalScore += score;

                if (score > stats.bestScore) stats.bestScore = score;
                if (time > 0 && time < stats.bestTime) stats.bestTime = time;
            }
        }

        if (stats.bestTime == Integer.MAX_VALUE) stats.bestTime = 0;

        //  Reading stats from username_stats.txt to get CompletedLevels or FiresExtinguished 
        File statsFile = new File(username + "_stats.txt");
        if (statsFile.exists()) {
            try (BufferedReader reader = new BufferedReader(new FileReader(statsFile))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    if (line.startsWith("CompletedLevels:")) {
                        String number = line.replace("CompletedLevels:", "").trim();
                        stats.completedLevels = Integer.parseInt(number);
                    }
                    else if (line.startsWith("FiresExtinguished:")) {
                        String number = line.replace("FiresExtinguished:", "").trim();
                        stats.firesExtinguished = Integer.parseInt(number);
                    }
                } 
            }catch (IOException e) {
                System.out.println("Error reading stats for " + username);
            }
        }

        return stats;
    }
    
    private ArrayList<String> readAllGames(String username) {
        //duplicating the method from ResultStats
        //to get every game in a file and returning a list, every file is a single player, this wil be useful to get the best player
        ArrayList<String> games = new ArrayList<>();
        File file = new File(username + "_games.txt");

        if (!file.exists()) return games;

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (!line.trim().isEmpty()) {
                    games.add(line.trim());
                }
            }
        } catch (IOException e) {
            System.out.println("Error reading games for " + username);
        }

        return games;
    }



    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel achievementsLBL;
    private javax.swing.JScrollPane achievementsScroll;
    private javax.swing.JTextArea achievementsTXT;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel bestPlayerLBL;
    private javax.swing.JLabel bestScoreLBL;
    private javax.swing.JLabel bestTimeLBL;
    private javax.swing.JLabel firesExtinguishedLBL;
    private javax.swing.JLabel totalGamesLBL;
    private javax.swing.JLabel totalScoreLBL;
    // End of variables declaration//GEN-END:variables
}