/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Section3_Edgar;

import java.io.*;
import java.util.*;

/**
 *
 * @author Edgar Camacho
 */
public class ResultStatsPanel extends javax.swing.JPanel {
    
    //defining first an instance of the navController interface and the currentUser
    private NavController navigator;
    private String currentUser;

    /**
     * Creates new form PlayerStatsPanel
     */
    public ResultStatsPanel(NavController navigator) {
        this.navigator = navigator;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBTN = new javax.swing.JButton();
        averageScoreLBL = new javax.swing.JLabel();
        bestScoreLBL = new javax.swing.JLabel();
        bestTimeLBL = new javax.swing.JLabel();
        totalGamesLBL = new javax.swing.JLabel();
        titleLBL = new javax.swing.JLabel();
        saveBTN = new javax.swing.JButton();
        levelscompletedLBL = new javax.swing.JLabel();
        currentScoreLBL = new javax.swing.JLabel();
        livesusedLBL = new javax.swing.JLabel();
        refreshStatsBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyOfGameTA = new javax.swing.JTextArea();
        levelscompletedLBL1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(139, 174, 102));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        backBTN.setBackground(new java.awt.Color(0, 92, 59));
        backBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        backBTN.setForeground(new java.awt.Color(255, 255, 255));
        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        averageScoreLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        averageScoreLBL.setForeground(new java.awt.Color(255, 255, 255));
        averageScoreLBL.setText("Average Session Score: ");

        bestScoreLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bestScoreLBL.setForeground(new java.awt.Color(255, 255, 255));
        bestScoreLBL.setText("Best Session Score: ");

        bestTimeLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bestTimeLBL.setForeground(new java.awt.Color(255, 255, 255));
        bestTimeLBL.setText("Best Session Time: ");

        totalGamesLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalGamesLBL.setForeground(new java.awt.Color(255, 255, 255));
        totalGamesLBL.setText("Total Sessions Played: ");

        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(255, 255, 255));
        titleLBL.setText("Player Statistics");

        saveBTN.setBackground(new java.awt.Color(0, 92, 59));
        saveBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        saveBTN.setForeground(new java.awt.Color(255, 255, 255));
        saveBTN.setText("Save");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        levelscompletedLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        levelscompletedLBL.setForeground(new java.awt.Color(255, 255, 255));
        levelscompletedLBL.setText("Total Levels Completed: ");

        currentScoreLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        currentScoreLBL.setForeground(new java.awt.Color(255, 255, 255));
        currentScoreLBL.setText("Current Session Score:");

        livesusedLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        livesusedLBL.setForeground(new java.awt.Color(255, 255, 255));
        livesusedLBL.setText("Total Lives Lost: ");

        refreshStatsBTN.setBackground(new java.awt.Color(0, 92, 59));
        refreshStatsBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        refreshStatsBTN.setForeground(new java.awt.Color(255, 255, 255));
        refreshStatsBTN.setText("Refresh Stats");
        refreshStatsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshStatsBTNActionPerformed(evt);
            }
        });

        historyOfGameTA.setColumns(20);
        historyOfGameTA.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        historyOfGameTA.setRows(5);
        jScrollPane1.setViewportView(historyOfGameTA);

        levelscompletedLBL1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        levelscompletedLBL1.setForeground(new java.awt.Color(255, 255, 255));
        levelscompletedLBL1.setText("Session Logs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(levelscompletedLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(496, 496, 496))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(refreshStatsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(saveBTN))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(livesusedLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(levelscompletedLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bestTimeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bestScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(averageScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalGamesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(732, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(totalGamesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelscompletedLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(livesusedLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(averageScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bestScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(currentScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bestTimeLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(levelscompletedLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshStatsBTN)
                    .addComponent(saveBTN))
                .addGap(128, 128, 128))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("MainMenu");
        }
    }//GEN-LAST:event_backBTNActionPerformed

    //here we called savePlayerstats
    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        savePlayerStats(currentUser);
    }//GEN-LAST:event_saveBTNActionPerformed

    //here we are gonna reload everything from the files, for a specific user
    private void refreshStatsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshStatsBTNActionPerformed
        // TODO add your handling code here:
        loadPlayerStats(currentUser);
    }//GEN-LAST:event_refreshStatsBTNActionPerformed

        //Useful for calculating totalstats, bestscore, and so on in the load method
        //This same method can be used in GameStatsPanel, duplicating it so its avoid the creation of more classes    
    private List<String> readAllGames(String username){
        List<String> games = new ArrayList<>();
        try{
            File game = new File(username + "_games.txt");
            //this needs to be appended by section 2 - Game logic so we can keep track of the wins            
            if(!game.exists()){
                return games;
            }
            BufferedReader reader = new BufferedReader(new FileReader(game));
            String line;
            while ((line = reader.readLine()) != null){
                if (!line.trim().isEmpty()) {
                    games.add(line.trim());
                }
            }
            reader.close();
        } catch (IOException e){
            System.out.println("Error reading games: " + e.getMessage());
        }
        return games;   //getting all the games played by the user
    }
    
    //overwrites the file that section 1 creates, to keep track of the user
     private void savePlayerStats(String username) {
        try {
            File file = new File(username + "_stats.txt");
            PrintWriter writer = new PrintWriter(new FileWriter(file));

            writer.println("CompletedLevels:" + levelscompletedLBL.getText().replace("Levels Completed: ", "").trim());
            writer.println("FiresExtinguished:" + livesusedLBL.getText().replace("Fires Extinguished: ", "").trim());
            writer.println("TotalScore:" + currentScoreLBL.getText().replace("Current Score: ", "").trim());

            writer.close();
            historyOfGameTA.setText("Player stats saved successfully for: " + username);

        } catch (IOException e) {
            historyOfGameTA.setText("Error saving player stats: " + e.getMessage());
        }
    }


    
    //This method is in charge of displaying the information and can be called from other panels
     //also calculates values such as totalscore, bestscore values     
    public void loadPlayerStats(String username) {
        this.currentUser = username;
        titleLBL.setText("Player Statistics - " + username);
        
        try {
            File statsFile = new File(username + "_stats.txt");
            if (statsFile.exists()) {
                BufferedReader reader = new BufferedReader(new FileReader(statsFile));
                String line;
                
                while ((line = reader.readLine()) != null) {
                    String[] statsTextParts = line.split(":");
                    if (statsTextParts.length == 2) {
                        switch (statsTextParts[0]) {
                            case "CompletedLevels":
                                levelscompletedLBL.setText("Levels Completed: " + statsTextParts[1]);
                                break;

                            case "FiresExtinguished":
                                livesusedLBL.setText("Fires Extinguished: " + statsTextParts[1]);
                                break;

                            case "TotalScore":
                                currentScoreLBL.setText("Current Score: " + statsTextParts[1]);
                                break;
                        }
                    }
                }
                reader.close();
            }
        } catch (IOException e) {
            System.out.println("Error loading player stats: " + e.getMessage());
        }
        
    
        List<String> allGames = readAllGames(this.currentUser);
        //restore the last gamesStats for a player (win-lose) in case hasnt played yet
        
        if (allGames.isEmpty()) {
            historyOfGameTA.setText("No games played yet for: " + username);
            totalGamesLBL.setText("Total Games Played: 0");
            bestScoreLBL.setText("Best Score: 0");
            averageScoreLBL.setText("Average Score: 0");
            bestTimeLBL.setText("Best Time: 0s");
            return;
        }
        
        int totalGames = allGames.size();
        int bestScore = 0;
        int totalScore = 0;
        int bestTime = Integer.MAX_VALUE;
        StringBuilder historyText = new StringBuilder();
        
        for (String game : allGames) {
            String[] parts = game.split(",");
            if (parts.length >= 3) {
                int score = Integer.parseInt(parts[0]);
                int time = Integer.parseInt(parts[1]);

                historyText.append("Score: ").append(score)
                          .append(" | Time: ").append(time).append("s")
                          .append(" | ").append(parts[2]).append("\n");

                // Update best score
                if (score > bestScore) bestScore = score;

                // Add into total for average score later
                totalScore += score;

                // Update best time
                if (time > 0 && time < bestTime) bestTime = time;
            }
        }
        
        int averageScore = totalScore / totalGames;
        
        totalGamesLBL.setText("Total Sessions Played: " + totalGames);
        bestScoreLBL.setText("Best Session Score: " + bestScore);
        averageScoreLBL.setText("Average Session Score: " + averageScore);
        bestTimeLBL.setText("Fastest Session Time: " + (bestTime == Integer.MAX_VALUE ? "0" : bestTime) + "s");
        historyOfGameTA.setText(historyText.toString());
    }
    
    // Records the game result to the players stats file
    public void recordGameResult(String username, int score, int time, boolean won) {
        try (PrintWriter writer = new PrintWriter(new FileWriter(username + "_games.txt", true))) {
            writer.println(score + "," + time + "," + (won ? "Win" : "Lose"));
        } catch (IOException e) {
            System.out.println("Error saving game result");
        }
        loadPlayerStats(username);
    }
    
    // Updates stats from the session
    public void showSessionStats(String username, int score, int time, int fires, int levels, int waterUsed) {

        this.currentUser = username;

        titleLBL.setText("Session Results - " + username);

        // Updates displayed values
        currentScoreLBL.setText("Curren Session Score: " + score);
        bestTimeLBL.setText("Fastest Session Time: " + time + "s");
        livesusedLBL.setText("Fires Extinguished: " + fires);
        levelscompletedLBL.setText("Total Levels Completed: " + levels);

        historyOfGameTA.setText(
            "This session summary:\n" +
            "- Total Score: " + score + "\n" +
            "- Total Time: " + time + " seconds\n" +
            "- Fires Extinguished: " + fires + "\n" +
            "- Levels Completed: " + levels
        );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel averageScoreLBL;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel bestScoreLBL;
    private javax.swing.JLabel bestTimeLBL;
    private javax.swing.JLabel currentScoreLBL;
    private javax.swing.JTextArea historyOfGameTA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel levelscompletedLBL;
    private javax.swing.JLabel levelscompletedLBL1;
    private javax.swing.JLabel livesusedLBL;
    private javax.swing.JButton refreshStatsBTN;
    private javax.swing.JButton saveBTN;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JLabel totalGamesLBL;
    // End of variables declaration//GEN-END:variables
}
