/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Section3_Edgar;

import Section1_Sam.MainFrame;
import java.io.*;
import java.util.*;

/**
 *
 * @author Edgar Camacho
 */
public class ResultStatsPanel extends javax.swing.JPanel {
    
    //defining first an instance of the navController interface and the currentUser
    private NavController navigator;
    private String currentUser;

    /**
     * Creates new form PlayerStatsPanel
     */
    public ResultStatsPanel(NavController navigator) {
        this.navigator = navigator;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBTN = new javax.swing.JButton();
        averageScoreLBL = new javax.swing.JLabel();
        bestScoreLBL = new javax.swing.JLabel();
        bestTimeLBL = new javax.swing.JLabel();
        totalGamesLBL = new javax.swing.JLabel();
        titleLBL = new javax.swing.JLabel();
        saveBTN = new javax.swing.JButton();
        levelLBL = new javax.swing.JLabel();
        currentScoreLBL = new javax.swing.JLabel();
        livesLBL = new javax.swing.JLabel();
        waterLBL = new javax.swing.JLabel();
        experienceBar = new javax.swing.JProgressBar();
        refreshStatsBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyOfGameTA = new javax.swing.JTextArea();
        nextlevelBTN = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(139, 174, 102));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        backBTN.setBackground(new java.awt.Color(0, 92, 59));
        backBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        backBTN.setForeground(new java.awt.Color(255, 255, 255));
        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        averageScoreLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        averageScoreLBL.setForeground(new java.awt.Color(255, 255, 255));
        averageScoreLBL.setText("Average Score: ");

        bestScoreLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bestScoreLBL.setForeground(new java.awt.Color(255, 255, 255));
        bestScoreLBL.setText("Best Score: ");

        bestTimeLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bestTimeLBL.setForeground(new java.awt.Color(255, 255, 255));
        bestTimeLBL.setText("Best Time: ");

        totalGamesLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalGamesLBL.setForeground(new java.awt.Color(255, 255, 255));
        totalGamesLBL.setText("Total Games Played: ");

        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(255, 255, 255));
        titleLBL.setText("Player Statistics");

        saveBTN.setBackground(new java.awt.Color(0, 92, 59));
        saveBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        saveBTN.setForeground(new java.awt.Color(255, 255, 255));
        saveBTN.setText("Save");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        levelLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        levelLBL.setForeground(new java.awt.Color(255, 255, 255));
        levelLBL.setText("Level: ");

        currentScoreLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        currentScoreLBL.setForeground(new java.awt.Color(255, 255, 255));
        currentScoreLBL.setText("Current Score:");

        livesLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        livesLBL.setForeground(new java.awt.Color(255, 255, 255));
        livesLBL.setText("Lives: ");

        waterLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        waterLBL.setForeground(new java.awt.Color(255, 255, 255));
        waterLBL.setText("Water: ");

        refreshStatsBTN.setBackground(new java.awt.Color(0, 92, 59));
        refreshStatsBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        refreshStatsBTN.setForeground(new java.awt.Color(255, 255, 255));
        refreshStatsBTN.setText("Refresh Stats");
        refreshStatsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshStatsBTNActionPerformed(evt);
            }
        });

        historyOfGameTA.setColumns(20);
        historyOfGameTA.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        historyOfGameTA.setRows(5);
        jScrollPane1.setViewportView(historyOfGameTA);

        nextlevelBTN.setBackground(new java.awt.Color(0, 92, 59));
        nextlevelBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nextlevelBTN.setForeground(new java.awt.Color(255, 255, 255));
        nextlevelBTN.setText("Next Level");
        nextlevelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextlevelBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalGamesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bestScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bestTimeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(averageScoreLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                                        .addComponent(currentScoreLBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(levelLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(waterLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(livesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274)
                        .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(601, 601, 601)
                        .addComponent(experienceBar, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(nextlevelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(refreshStatsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveBTN))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(679, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(totalGamesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(averageScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(livesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(levelLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bestScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(currentScoreLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(waterLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bestTimeLBL)
                        .addGap(0, 113, Short.MAX_VALUE)))
                .addGap(50, 50, 50)
                .addComponent(experienceBar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshStatsBTN)
                    .addComponent(saveBTN)
                    .addComponent(nextlevelBTN))
                .addGap(96, 96, 96))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("MainMenu");
        }
    }//GEN-LAST:event_backBTNActionPerformed

    //here we called savePlayerstats
    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        savePlayerStats(currentUser);
    }//GEN-LAST:event_saveBTNActionPerformed

    //here we are gonna reload everything from the files, for a specific user
    private void refreshStatsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshStatsBTNActionPerformed
        // TODO add your handling code here:
        loadPlayerStats(currentUser);
    }//GEN-LAST:event_refreshStatsBTNActionPerformed

    private void nextlevelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextlevelBTNActionPerformed
        // TODO add your handling code here:
        if (navigator instanceof MainFrame frame) {
        frame.startNextLevel();
        }
    }//GEN-LAST:event_nextlevelBTNActionPerformed

        //Useful for calculating totalstats, bestscore, and so on in the load method
        //This same method can be used in GameStatsPanel, duplicating it so its avoid the creation of more classes    
    private List<String> readAllGames(String username){
        List<String> games = new ArrayList<>();
        try{
            File game = new File(username + "_games.txt");
            //this needs to be appended by section 2 - Game logic so we can keep track of the wins            
            if(!game.exists()){
                return games;
            }
            BufferedReader reader = new BufferedReader(new FileReader(game));
            String line;
            while ((line = reader.readLine()) != null){
                if (!line.trim().isEmpty()) {
                    games.add(line.trim());
                }
            }
            reader.close();
        } catch (IOException e){
            System.out.println("Error reading games: " + e.getMessage());
        }
        return games;   //getting all the games played by the user
    }
    
    //overwrites the file that section 1 creates, to keep track of the user
     private void savePlayerStats(String username) {
        try {
            File file = new File(username + "_stats.txt");
            PrintWriter writer = new PrintWriter(new FileWriter(file));
            
            writer.println("Username:" + username);
            writer.println("Level:" + levelLBL.getText().replace("Level: ", ""));
            writer.println("Score:" + currentScoreLBL.getText().replace("Current Score: ", ""));
            writer.println("Lives:" + livesLBL.getText().replace("Lives: ", ""));
            writer.println("Water:" + waterLBL.getText().replace("Water: ", ""));
            writer.println("Experience:" + experienceBar.getValue());
            
            writer.close();
            historyOfGameTA.setText("Player stats saved successfully for: " + username);
        } catch (IOException e) {
            historyOfGameTA.setText("Error saving player stats: " + e.getMessage());
        }
    }
    
    //This method is in charge of displaying the information and can be called from other panels
     //also calculates values such as totalscore, bestscore values     
     public void loadPlayerStats(String username) {
        this.currentUser = username;
        titleLBL.setText("Player Statistics - " + username);
        
        try {
            File statsFile = new File(username + "_stats.txt");
            if (statsFile.exists()) {
                BufferedReader reader = new BufferedReader(new FileReader(statsFile));
                String line;
                
                while ((line = reader.readLine()) != null) {
                    String[] statsTextParts = line.split(":");
                    if (statsTextParts.length == 2) {
                        switch (statsTextParts[0]) {
                            case "Username":
                                break;
                            case "Level":
                                levelLBL.setText("Level: " + statsTextParts[1]);
                                break;
                            case "Score":
                                currentScoreLBL.setText("Current Score: " + statsTextParts[1]);
                                break;
                            case "Lives":
                                livesLBL.setText("Lives: " + statsTextParts[1]);
                                break;
                            case "Water":
                                waterLBL.setText("Water: " + statsTextParts[1]);
                                break;
                            case "Experience":
                                experienceBar.setValue(Integer.parseInt(statsTextParts[1]));
                                experienceBar.setString("Experience: " + statsTextParts[1] + "%");
                                break;
                        }
                    }
                }
                reader.close();
            }
        } catch (IOException e) {
            System.out.println("Error loading player stats: " + e.getMessage());
        }
        
    
        List<String> allGames = readAllGames(this.currentUser);
        //restore the last gamesStats for a player (win-lose) in case hasnt played yet
        
        if (allGames.isEmpty()) {
            historyOfGameTA.setText("No games played yet for: " + username);
            totalGamesLBL.setText("Total Games Played: 0");
            bestScoreLBL.setText("Best Score: 0");
            averageScoreLBL.setText("Average Score: 0");
            bestTimeLBL.setText("Best Time: 0s");
            return;
        }
        
        int totalGames = allGames.size();
        int bestScore = 0;
        int totalScore = 0;
        int bestTime = Integer.MAX_VALUE;
        StringBuilder historyText = new StringBuilder();
        
        for (String game : allGames) {
            String[] parts = game.split(",");
            if (parts.length >= 3) {
                int score = Integer.parseInt(parts[0]);
                int time = Integer.parseInt(parts[1]);
                String result = parts[2];
                
                historyText.append("Score: ").append(score)
                          .append(" | Time: ").append(time).append("s")
                          .append(" | ").append(result).append("\n");
                
                if (score > bestScore) bestScore = score;
                totalScore += score;
                if (time < bestTime && time > 0) bestTime = time;
            }
        }
        
        int averageScore = totalScore / totalGames;
        
        totalGamesLBL.setText("Total Games Played: " + totalGames);
        bestScoreLBL.setText("Best Score: " + bestScore);
        averageScoreLBL.setText("Average Score: " + averageScore);
        bestTimeLBL.setText("Best Time: " + (bestTime == Integer.MAX_VALUE ? "0" : bestTime) + "s");
        historyOfGameTA.setText(historyText.toString());
    }
     
     public void updatePlayerStats(String username, int level, int score, int lives, int water, int experience) {
        this.currentUser = username;
        levelLBL.setText("Level: " + level);
        currentScoreLBL.setText("Current Score: " + score);
        livesLBL.setText("Lives: " + lives);
        waterLBL.setText("Water: " + water + "/30");
        experienceBar.setValue(experience);
        experienceBar.setString("Experience: " + experience + "%");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel averageScoreLBL;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel bestScoreLBL;
    private javax.swing.JLabel bestTimeLBL;
    private javax.swing.JLabel currentScoreLBL;
    private javax.swing.JProgressBar experienceBar;
    private javax.swing.JTextArea historyOfGameTA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel levelLBL;
    private javax.swing.JLabel livesLBL;
    private javax.swing.JButton nextlevelBTN;
    private javax.swing.JButton refreshStatsBTN;
    private javax.swing.JButton saveBTN;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JLabel totalGamesLBL;
    private javax.swing.JLabel waterLBL;
    // End of variables declaration//GEN-END:variables
}
