/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Section2;

import Section3_Edgar.NavController;

/**
 *
 * @author lwild_oeg6x3t
 */
public class GamePanel extends javax.swing.JPanel {

    private NavController navigator;
    /**
     * Creates new form GamePanel
     */
    public GamePanel(NavController navigator) {
        this.navigator = navigator;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pauseBTN = new javax.swing.JButton();
        scoreLBL = new javax.swing.JLabel();
        livesLBL = new javax.swing.JLabel();
        waterLBL = new javax.swing.JLabel();
        timerLBL = new javax.swing.JLabel();

        pauseBTN.setText("PAUSE");
        pauseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseBTNActionPerformed(evt);
            }
        });

        scoreLBL.setText("SCORE:");

        livesLBL.setText("LIVES:");

        waterLBL.setText("WATER LEFT:");

        timerLBL.setText("TIME LEFT:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pauseBTN)
                .addGap(62, 62, 62)
                .addComponent(livesLBL)
                .addGap(31, 31, 31)
                .addComponent(waterLBL)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scoreLBL)
                    .addComponent(timerLBL))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pauseBTN)
                    .addComponent(livesLBL)
                    .addComponent(waterLBL)
                    .addComponent(timerLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(scoreLBL)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pauseBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseBTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("PauseMenu");
        }
    }//GEN-LAST:event_pauseBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel livesLBL;
    private javax.swing.JButton pauseBTN;
    private javax.swing.JLabel scoreLBL;
    private javax.swing.JLabel timerLBL;
    private javax.swing.JLabel waterLBL;
    // End of variables declaration//GEN-END:variables
}
