/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Section2;

import Section3.NavController;

/**
 *
 * @author Lance Wilde
 */
public class LevelSelectPanel extends javax.swing.JPanel {

    private NavController navigator;
    /**
     * Creates new form LevelSelectPanel
     */
    public LevelSelectPanel(NavController navigator) {
        this.navigator = navigator;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        level1BTN = new javax.swing.JButton();
        levelselectLBL = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();
        level3BTN = new javax.swing.JButton();
        level2BTN = new javax.swing.JButton();

        level1BTN.setText("Level 1");
        level1BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level1BTNActionPerformed(evt);
            }
        });

        levelselectLBL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        levelselectLBL.setText("Level Select");

        backBTN.setText("BACK");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        level3BTN.setText("Level 3");
        level3BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level3BTNActionPerformed(evt);
            }
        });

        level2BTN.setText("Level 2");
        level2BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level2BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(level1BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(level2BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBTN)
                        .addGap(56, 56, 56)
                        .addComponent(levelselectLBL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(level3BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBTN)
                    .addComponent(levelselectLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(level1BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(level2BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(level3BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("MainMenu");
        }
    }//GEN-LAST:event_backBTNActionPerformed

    private void level1BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level1BTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("Game");
        }
    }//GEN-LAST:event_level1BTNActionPerformed

    private void level2BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level2BTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("Game");
        }
    }//GEN-LAST:event_level2BTNActionPerformed

    private void level3BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level3BTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("Game");
        }
    }//GEN-LAST:event_level3BTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton level1BTN;
    private javax.swing.JButton level2BTN;
    private javax.swing.JButton level3BTN;
    private javax.swing.JLabel levelselectLBL;
    // End of variables declaration//GEN-END:variables
}
