/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Section2;

import Section3_Edgar.NavController;

/**
 *
 * @author Lance Wilde
 */
public class PauseMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form PauseMenuPanel
     */
    private NavController navigator;
    /**
     * Creates new form LevelSelectPanel
     */
    public PauseMenuPanel(NavController navigator) {
        this.navigator = navigator;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resumeBTN = new javax.swing.JButton();
        mainmenuBTN = new javax.swing.JButton();
        settingsBTN = new javax.swing.JButton();

        resumeBTN.setText("RESUME");
        resumeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeBTNActionPerformed(evt);
            }
        });

        mainmenuBTN.setText("MAIN MENU");
        mainmenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuBTNActionPerformed(evt);
            }
        });

        settingsBTN.setText("SETTINGS");
        settingsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resumeBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainmenuBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(resumeBTN)
                .addGap(43, 43, 43)
                .addComponent(settingsBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(mainmenuBTN)
                .addGap(77, 77, 77))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resumeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeBTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("Game");
        }
    }//GEN-LAST:event_resumeBTNActionPerformed

    private void settingsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("Settings");
        }
    }//GEN-LAST:event_settingsBTNActionPerformed

    private void mainmenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuBTNActionPerformed
        // TODO add your handling code here:
        if (navigator != null){
            navigator.switchScreen("MainMenu");
        }
    }//GEN-LAST:event_mainmenuBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mainmenuBTN;
    private javax.swing.JButton resumeBTN;
    private javax.swing.JButton settingsBTN;
    // End of variables declaration//GEN-END:variables
}
