/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Section1_Sam; //Sook Ying Sam

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sam SY
 */
public class MainMenuPanel extends javax.swing.JPanel {
    private MainFrame mainFrame;
    String name;
    private ArrayList<Player> register;

    /**
     * Creates new form MainMenuPanel
     */
    public MainMenuPanel(MainFrame frame) {
        this.mainFrame = frame;
        initComponents();
        setSize(1920,1080);
        register = new ArrayList<>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLBL = new javax.swing.JLabel();
        playBTN = new javax.swing.JButton();
        levelBTN = new javax.swing.JButton();
        resultBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        nameLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        displayBTN = new javax.swing.JButton();
        gameStatsBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(139, 174, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        titleLBL.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        titleLBL.setText("Firefigher Game");

        playBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        playBTN.setText("PLAY");
        playBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBTNActionPerformed(evt);
            }
        });

        levelBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        levelBTN.setText("Level Select");
        levelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelBTNActionPerformed(evt);
            }
        });

        resultBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        resultBTN.setText("Result Stats ");
        resultBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultBTNActionPerformed(evt);
            }
        });

        exitBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        nameLBL.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        nameLBL.setText("Name");

        nameTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });

        addBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addBTN.setText("ADD");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        deleteBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deleteBTN.setText("DELETE");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        displayTA.setColumns(20);
        displayTA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        displayBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        displayBTN.setText("DISPLAY");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });

        gameStatsBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        gameStatsBTN.setText("Game Stats");
        gameStatsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameStatsBTNActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Section1_Sam/minionfirefighter.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBTN)
                .addGap(970, 970, 970))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(579, 579, 579)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(playBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exitBTN))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(472, 472, 472)
                                .addComponent(levelBTN)
                                .addGap(51, 51, 51)
                                .addComponent(resultBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gameStatsBTN))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(527, 527, 527)
                                .addComponent(nameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleLBL)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(displayBTN))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteBTN)))
                        .addGap(103, 103, 103)))
                .addComponent(jLabel1)
                .addGap(556, 556, 556))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(titleLBL)
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLBL)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(addBTN)
                        .addGap(39, 39, 39)
                        .addComponent(displayBTN)))
                .addGap(34, 34, 34)
                .addComponent(deleteBTN)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playBTN)
                            .addComponent(exitBTN))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(levelBTN)
                            .addComponent(resultBTN)
                            .addComponent(gameStatsBTN)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(345, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0); //exit the hold game page
        
    }//GEN-LAST:event_exitBTNActionPerformed

    private void playBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBTNActionPerformed
        // TODO add your handling code here:
        if(mainFrame != null){
            mainFrame.showScreen("Game"); //when clicked, switched to the game screen
        }
    }//GEN-LAST:event_playBTNActionPerformed

    private void levelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelBTNActionPerformed
        // TODO add your handling code here:
        if(mainFrame != null){
            mainFrame.showScreen("LevelSelect"); //switched to the level select page
        }
    }//GEN-LAST:event_levelBTNActionPerformed

    private void resultBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultBTNActionPerformed
        // TODO add your handling code here:
        if(mainFrame != null){
            String playerName = nameTF.getText().trim();
            
            if(!playerName.isEmpty()) {
            File playerFile = new File(playerName + "_stats.txt"); //create a file when player is registered
            if(playerFile.exists()) {
                System.out.println("Loading stats for: " + playerName); 
                mainFrame.showResultsStats(playerName); //shown specific player result in resultStats page
            } else {
                displayTA.setText("Player '" + playerName + "' not found. Please ADD player first.");
                System.out.println("File not found: " + playerFile.getAbsolutePath()); // Debug
            }
        } else {
            displayTA.setText("Please enter a player name first.");
        }
        }
    }//GEN-LAST:event_resultBTNActionPerformed
    
    
                                              
    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        //create and add player
        String name = nameTF.getText().trim();
        if (!name.isEmpty()) {
            Player tempP = new Player(name);
            register.add(tempP);
            savePlayerToFile(tempP);  
            displayTA.setText("New Player Registered: " + name);
        }        
    }//GEN-LAST:event_addBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        if(register.isEmpty()){
             displayTA.setText("No players registered");
         }else{
             String searchTerm = JOptionPane.showInputDialog(null, "Enter Name to be deleted"); //enter player name to search
             for(int i = 0; i < register.size(); i++){
                 Player tempP = register.get(i);
                 if(tempP.getName().equalsIgnoreCase(searchTerm)){ //get the name that entered by user and delete the player
                     register.remove(i);
                     displayTA.setText("Player " + searchTerm + " has been removed.");
                 }
             }
         }
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
        if(register.isEmpty()){
            displayTA.setText("No players registered.");
        }else{
            for(Player p:register){ //forEach loop
                JOptionPane.showMessageDialog(null, p.printDetails());
            }
        }
    }//GEN-LAST:event_displayBTNActionPerformed

    private void gameStatsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameStatsBTNActionPerformed
        // TODO add your handling code here:
        if(mainFrame != null){
        mainFrame.showScreen("GameStats"); //switched to gameStats screen
    }
    }//GEN-LAST:event_gameStatsBTNActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed
    //save the player's stats into a text file
    private void savePlayerToFile(Player player) {
    try {
        File file = new File(player.getName() + "_stats.txt");
        PrintWriter writer = new PrintWriter(new FileWriter(file)); //opens a "writer" that can write text into the file
        
        //write default starting stats for the player
        writer.println("Level:1");
        writer.println("Score:0");
        writer.println("Lives:3");
        writer.println("Water:100");
        writer.println("Experience:0");
        
        writer.close(); //saves and closes the file
    } catch (IOException e) {
        System.out.println("Error saving player: " + e.getMessage());
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton displayBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JButton exitBTN;
    private javax.swing.JButton gameStatsBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton levelBTN;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton playBTN;
    private javax.swing.JButton resultBTN;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
